server:
  port: 9090

spring:
  application:
    name: msvc-categories

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:categoriesDB
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
